dist: xenial
language: go

addons:
  postgresql: '9.6'

go:
  - 1.13.x
  - 1.14.x
  - tip

matrix:
  allow_failures:
    - go: tip

env:
  - GO111MODULE=on

go_import_path: github.com/go-pg/pg

before_install:
  - psql -U postgres -c "CREATE EXTENSION hstore"
  - curl -sSfL
    https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |
    sh -s -- -b $(go env GOPATH)/bin v1.27.0
