dist: trusty
language: go

addons:
  postgresql: "9.6"

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - psql -U postgres -c "CREATE EXTENSION hstore"

install:
  - go get github.com/jinzhu/inflection
  - go get gopkg.in/check.v1
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/vmihailenco/sasl
