dist: xenial
sudo: false
language: go

addons:
  postgresql: "9.6"

go:
  - 1.12.x
  - 1.13.x
  - tip

matrix:
  allow_failures:
    - go: tip

env:
  - GO111MODULE=on

go_import_path: github.com/go-pg/pg

before_install:
  - psql -U postgres -c "CREATE EXTENSION hstore"
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.19.0
